#!/usr/bin/env python3
"""Single source for the platform topic inventory (audit B10).

Reads contracts/events/topics.json (domain topics -> schema files) and
contracts/events/consumers.json (consumer groups -> consumed topics) and
generates every place that previously hand-maintained the list:

  - infra/kafka/create-topics.sh          (domain + DLQ topic creation)
  - contracts/gen/go/events/topics.go     (Go consumers, e.g. audit firehose)

Run: python3 scripts/gen-topics.py          # regenerate
     python3 scripts/gen-topics.py --check  # exit 1 if outputs are stale
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EVENTS = ROOT / "contracts" / "events"

GENERATED_NOTE = "GENERATED by scripts/gen-topics.py from contracts/events/{topics,consumers}.json — do not edit"


def load():
    topics = json.loads((EVENTS / "topics.json").read_text())
    consumers = json.loads((EVENTS / "consumers.json").read_text())
    consumers.pop("_comment", None)

    for topic, schema in topics.items():
        if not (EVENTS / schema).is_file():
            sys.exit(f"topics.json: {topic} -> {schema} does not exist")
    for group, spec in consumers.items():
        if spec["topics"] == "*":
            continue
        for topic in spec["topics"]:
            if topic not in topics:
                sys.exit(f"consumers.json: {group} consumes unknown topic {topic}")
    return topics, consumers


def dlq_topics(consumers):
    out = []
    for group, spec in consumers.items():
        if spec["topics"] == "*":
            out.append(spec["dlq"])
        else:
            out.extend(f"{group}.{topic}.dlq" for topic in spec["topics"])
    return out


def render_script(topics, consumers):
    lines = [
        "#!/bin/bash",
        f"# {GENERATED_NOTE}",
        "# Creates all peikonpurekkusu topics idempotently.",
        "# Naming: <domain>.<aggregate>.<event>.v<N> — keyed by aggregate id.",
        "# DLQs are per consumer group: <group>.<topic>.dlq",
        "set -euo pipefail",
        "",
        'BOOTSTRAP="${BOOTSTRAP:-kafka:19092}"',
        "KT=/opt/kafka/bin/kafka-topics.sh",
        'PARTITIONS="${PARTITIONS:-3}"',
        'RF="${RF:-1}"   # 3 in the ha profile',
        "",
        "create() {",
        '  local topic="$1"; shift',
        '  $KT --bootstrap-server "$BOOTSTRAP" --create --if-not-exists \\',
        '    --topic "$topic" --partitions "$PARTITIONS" --replication-factor "$RF" "$@"',
        "}",
        "",
        "# Domain event topics (facts)",
    ]
    lines += [f"create {topic}" for topic in sorted(topics)]
    lines += ["", "# Per-consumer-group dead letter queues"]
    lines += [f"create {topic}" for topic in dlq_topics(consumers)]
    lines += [
        "",
        'echo "── topics ──"',
        '$KT --bootstrap-server "$BOOTSTRAP" --list',
        'echo "── done ──"',
        "",
    ]
    return "\n".join(lines)


def render_go(topics, consumers):
    lines = [
        f"// Package events is the platform topic inventory. {GENERATED_NOTE}.",
        "package events",
        "",
        "// Topics lists every domain event topic (the audit firehose).",
        "var Topics = []string{",
    ]
    lines += [f"\t\"{topic}\"," for topic in sorted(topics)]
    lines += [
        "}",
        "",
        "// DLQTopics lists every dead-letter topic, derived per consumer group.",
        "var DLQTopics = []string{",
    ]
    lines += [f"\t\"{topic}\"," for topic in dlq_topics(consumers)]
    lines += ["}", ""]
    return "\n".join(lines)


def main():
    topics, consumers = load()
    outputs = {
        ROOT / "infra" / "kafka" / "create-topics.sh": render_script(topics, consumers),
        ROOT / "contracts" / "gen" / "go" / "events" / "topics.go": render_go(topics, consumers),
    }
    if "--check" in sys.argv:
        stale = [str(p) for p, want in outputs.items()
                 if not p.is_file() or p.read_text() != want]
        if stale:
            sys.exit("stale generated topic lists (run scripts/gen-topics.py): " + ", ".join(stale))
        print("topic lists in sync")
        return
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
